import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

function Home({ images }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>React/Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Seja bem vindo!</h1>

        <div className={styles.grid}>
          {images &&
            images.slice(0, 9).map((image) => (
              <a href="https://nextjs.org/docs" key={image.id} className={styles.card}>
                <h2>Documentation &rarr;</h2>
                <Image src={image.url} width={100} height={100} />
              </a>
            ))}
        </div>
      </main>
    </div>
  );
}

Home.getInitialProps = async (ctx) => {
  const res = await fetch("https://jsonplaceholder.typicode.com/photos");
  const json = await res.json();
  return { images: json };
};

export default Home;
